[package]
name = "aardwolf-api"
version = "0.1.0"
<<<<<<< HEAD
edition = "2021"
=======
edition = "2024"

[workspace]
members = [
    "aardwolf-api-common",
    "backend-api",
    "database-api",
    "frontend-api",
]

[dependencies]
aardwolf-api-common = { path = "aardwolf-api-common" }

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
>>>>>>> d1b24ddd5f52965698d08e47af9333a61cbcc526
